# To run: conda env create -f environment.yml
name: activenerf
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - torch>=1.4.0
    - torchvision>=0.2.1
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - configargparse
    - tensorboard==1.15.0
    - tqdm
    - opencv-python
