# To run: conda env create -f environment.yml
# FIXME: opencv and torch not working correctly- next change will be putting a specific conda-forge channel for opencv-python/ using cv2
name: activenerf
channels:
    - pypi
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - pip
    - torch==1.4.0 # changed from being >= to ==
    - torchvision>=0.2.1
    - imageio
    - imageio-ffmpeg
    - matplotlib
    - configargparse
    - tensorboard==1.15.0
    - tqdm
    - pip: # replacing opencv-python + numba and GPUtil added
      - numba
      - GPUtil
      - opencv-contrib-python==4.6.0.66
